// <auto-generated />
using BlazorAppOluja.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppOluja.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230808084602_Categories")]
    partial class Categories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorAppOluja.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Operacije",
                            Url = "books"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pomoc",
                            Url = "pomoc"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vojna Tehnika",
                            Url = "vojna-tehnika"
                        });
                });

            modelBuilder.Entity("BlazorAppOluja.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Knin pobjeda",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/ed/16_obljetnica_vojnoredarstvene_operacije_Oluja_05082011_Kninska_tvrdjava_155.jpg",
                            Price = 9.99m,
                            Title = "Knin"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Predaja Čede Bulata",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/hr/4/43/Predaja_21.korpusa_SVK_1995.jpg",
                            Price = 7.99m,
                            Title = "Mile"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Operacija Oluja 95",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Map_49_-_Croatia_-_Operation_Oluja%2C_4-8_August_1995.jpg/800px-Map_49_-_Croatia_-_Operation_Oluja%2C_4-8_August_1995.jpg",
                            Price = 8.99m,
                            Title = "Oluja"
                        });
                });

            modelBuilder.Entity("BlazorAppOluja.Shared.Product", b =>
                {
                    b.HasOne("BlazorAppOluja.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
