// <auto-generated />
using BlazorAppOluja.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppOluja.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230805164537_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorAppOluja.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Knin pobjeda",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/ed/16_obljetnica_vojnoredarstvene_operacije_Oluja_05082011_Kninska_tvrdjava_155.jpg",
                            Price = 9.99m,
                            Title = "Knin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Predaja Milana Martića",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/hr/4/43/Predaja_21.korpusa_SVK_1995.jpg",
                            Price = 7.99m,
                            Title = "Mile"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Operacija Oluja 95",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Map_49_-_Croatia_-_Operation_Oluja%2C_4-8_August_1995.jpg/800px-Map_49_-_Croatia_-_Operation_Oluja%2C_4-8_August_1995.jpg",
                            Price = 8.99m,
                            Title = "Oluja"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
